version = 0.1

[default.deploy.parameters]
stack_name = "your-stack-name"
s3_bucket = "your-s3-bucket"
s3_prefix = "your-prefix"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
parameter_overrides = "Stage=dev"
