version = 0.1

[default.deploy.parameters]
stack_name = "identity-service-dev"
resolve_s3 = true
s3_prefix = "identity-service-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
